### ISSUE TITLE
Is there a discrepancy in the type of service name?

### ISSUE THREAD

**Issue by fgriberi** [shoppimon/majortomo#1]
The [client.send](https://github.com/shoppimon/majortomo/blob/master/majortomo/client.py#L79) expect a service_name as `bytes` but the [worker](https://github.com/shoppimon/majortomo/blob/master/majortomo/worker.py#L37) expects a `str`. 
Would it be possible to support the same type on both sides or maybe better support both?

**Comment by shevron** [comment]
I can confirm this is an issue, and will try to fix. Most likely, we'd want to support both `bytes` and `str` as input in both. Need to ensure we don't (yet) break Python 2.7 support here as well.

**Comment by shevron** [comment]
This should be fixed by #2

**Comment by fgriberi** [comment]
👍 thank you so much @shevron
